[package]
name = "Kirian"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
shaderc = "0.8"
image = "0.24"

# Reduce perfoamance artifacts from debug
[profile.dev]
opt-level = 1